soccer_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    #path('soccerstats/', include('soccerstats.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views 

app_name ='users'

urlpatterns = [
    path('', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('users/', views.home, name="home"),
    path('users/matches', views.matches, name="matches"),
    path('users/favorites', views.favorites, name="favorites"),
    path('users/editfavorites', views.editfavorites, name="editfavorites"),
    
]

users/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE

class Team(models.Model):
    name = models.CharField(max_length=100, null=True)
    team_id = models.IntegerField(null=True)
    logo = models.URLField(null=True)

    def __str__(self):
        return self.name

class Favorites(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    teams = models.ManyToManyField(Team)

    def __str__(self):
        return self.user.username

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from decouple import config
from operator import itemgetter
from .models import Team
import requests
import datetime
import json 
import pdb; 

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('users:home')

    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user_name = form.cleaned_data.get('username')
            messages.success(request, 'Account was successfully created for ' + user_name+'.' + ' You can log in now!')
            return redirect('users:login')

    context = {'form':form}
    return render(request, 'users/signup.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('users:home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('users:home')
        else:
            messages.info(request, 'Username OR password is incorrect!')

    context = {}
    return render(request, 'users/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('users:login')


#store teams info in database from first call
@login_required(login_url='users:login')
def home(request):
    
    search_result = {}

    url = "https://api-football-v1.p.rapidapi.com/v3/standings"

    query = {"season":"2021","league":"39"}
    #add dynamic season entry functionality

    headers = {
    'x-rapidapi-key': config('RAPID_API_KEY'),
    'x-rapidapi-host': 'api-football-v1.p.rapidapi.com'
    }

    response = requests.get(url, headers=headers, params=query)

    if response.status_code == 200:  # SUCCESS
        search_result = response.json()
        search_result['success'] = True
        search_result['rate'] = {
            'limit': response.headers['x-ratelimit-requests-limit'],
            'remaining': response.headers['x-ratelimit-requests-remaining'],
        }
    else:
        search_result['success'] = False
        if response.status_code == 404:  # NOT FOUND
            search_result['message'] = 'API-FOOTBALL services are not available at the moment. Please try again later.'

    context = {'search_result': search_result}
    return render(request, 'users/home.html', context)

#clean up this code when done i.e. use js_string and rename to search_result
@login_required(login_url='users:login')
def matches(request):
    
    search_result = {}

    url = "https://api-football-v1.p.rapidapi.com/v3/fixtures"

    query = {"league":"39","season":"2021","timezone":"America/New_York","from":"2021-08-12","to":"2021-11-01"} 

    headers = {
    'x-rapidapi-key': config('RAPID_API_KEY'),
    'x-rapidapi-host': 'api-football-v1.p.rapidapi.com'
    }

    response = requests.get(url, headers=headers, params=query)

    js_string = json.loads(response.text)

    if response.status_code == 200:  # SUCCESS
        search_result = response.json()
        search_result['success'] = True
        search_result['rate'] = {
            'limit': response.headers['x-ratelimit-requests-limit'],
            'remaining': response.headers['x-ratelimit-requests-remaining'],
        }
    else:
        search_result['success'] = False
        if response.status_code == 404:  # NOT FOUND
            search_result['message'] = 'API-FOOTBALL services are not available at the moment. Please try again later.'
    
    for times in js_string['response']:
        time_obj = datetime.datetime.strptime(times['fixture']['date'], "%Y-%m-%dT%H:%M:%S%z")
        time_time = time_obj.time()
        time_date = time_obj.date()
        times['date'] = time_date.strftime("%A, %B %d, %Y")
        times['time'] = time_time.strftime("%-I:%M %p")

    js_string['response'] = sorted(js_string['response'], key=lambda k: k['fixture']['date'])

    context = {'search_result': search_result, "js_string": js_string}
    return render(request, 'users/matches.html', context)


@login_required(login_url='users:login')
def favorites(request):

    search_result = {}

    url = "https://api-football-v1.p.rapidapi.com/v3/fixtures"

    query = {"league":"39","season":"2021","timezone":"America/New_York","from":"2021-08-12","to":"2021-11-01"} 
    
    headers = {
    'x-rapidapi-key': config('RAPID_API_KEY'),
    'x-rapidapi-host': 'api-football-v1.p.rapidapi.com'
    }

    response = requests.get(url, headers=headers, params=query)

    js_string_fav = json.loads(response.text)

    user_team_ids = list(request.user.favorites.teams.all().values_list('team_id', flat=True))

    if response.status_code == 200:  # SUCCESS
        search_result = response.json()
        search_result['success'] = True
        search_result['rate'] = {
            'limit': response.headers['x-ratelimit-requests-limit'],
            'remaining': response.headers['x-ratelimit-requests-remaining'],
        }
    else:
        search_result['success'] = False
        if response.status_code == 404:  # NOT FOUND
            search_result['message'] = 'API-FOOTBALL services are not available at the moment. Please try again later.'


    for times in js_string_fav['response']:
   
        time_obj = datetime.datetime.strptime(times['fixture']['date'], "%Y-%m-%dT%H:%M:%S%z")
        time_time = time_obj.time()
        time_date = time_obj.date()
        times['date'] = time_date.strftime("%A, %B %d, %Y")
        times['time'] = time_time.strftime("%-I:%M %p")
    

    js_string_fav['response'] = sorted(js_string_fav['response'], key=lambda k: k['fixture']['date'])


    for items in js_string_fav['response'][:]:
        if items['teams']['home']['id'] not in user_team_ids and items['teams']['away']['id'] not in user_team_ids:
            js_string_fav['response'].remove(items)
    
    context = {'search_result': search_result, "js_string_fav": js_string_fav}
    return render(request, 'users/favorites.html', context)


@login_required(login_url='users:login')
def editfavorites(request):

    user = request.user
    current_teams = list(user.favorites.teams.all().values_list('team_id', flat=True))

    if request.method == "POST":
        data = request.POST.values()
        selected_ids = list(data)

        for x in current_teams:
            if x not in selected_ids:
                team = Team.objects.get(team_id=x)
                user.favorites.teams.remove(team)
                user.save()

        for x in selected_ids[1:]:
            if x not in current_teams:
                team = Team.objects.get(team_id=x)
                user.favorites.teams.add(team)
                user.save()

        return redirect('users:favorites')

    all_teams = Team.objects.all()
    context = {'all_teams': all_teams, 'current_teams': current_teams}
    return render(request, 'users/editfavorites.html', context)

users/templates/users/base.html
<!DOCTYPE html>
{%load static%}
<html>
<head>
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'users/users.css' %}">
    <script src="{% static 'users/users.js' %}"></script>
    <script>    
    $(window).on('beforeunload', function() {
        $(window).scrollTop(0);
    });
    </script>
</head>
<body>
    <nav class="nav">
        <div class="container">
            <div class="logo">
                <a href="{% url 'users:home' %}">
                    <img alt="Premier League" src="../../static/users/NicePng_manchester-united-png_620282.png"/>
                </a>
            </div>
            <div id="mainListDiv" class="main_list">
                <ul class="navlinks">
                    <li><a href="{% url 'users:home' %}">Standings</a></li>
                    <li><a href="{% url 'users:matches' %}">Matches</a></li>
                    <li><a href="{% url 'users:favorites' %}">Favorites</a></li>
                    <li><a href="{% url 'users:logout' %}">Logout ({{ user.username }})</a></li>
                </ul>
            </div>
            <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </div>
    </nav>
    
    {% block content %}{% endblock content %}

    <!-- Function used to shrink nav bar removing paddings and adding color background -->
    <script>
    $(window).scroll(function() {
        if ($(document).scrollTop() > 50) {
            $('.nav').addClass('affix');
            console.log("OK");
        } else {
            $('.nav').removeClass('affix');
        }
    });
    </script>
</body>
</html>

users/templates/users/editfavorites.html
{% extends "users/base.html" %}
{%load static%}

{% block title %}
Edit Favorites
{% endblock title %}

{% block content %} 
<section class="home" style="background-image: url(https://images.unsplash.com/photo-1519823038424-f8dbabca95f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTYzMDA5MTQ5NA&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080);">
</section>

<div class="container paddings-mini" style="margin-right: 100px; margin-left: 100px; margin-bottom: 100px;">
    <h2 class="myH2">Edit Favorites</h2>
            <div class="row">
                <div class="col-lg-12">
                <form method="POST" action="">
                    {% csrf_token %}
                    <table class="table-striped table-responsive table-hover" style="width: 70%; margin-top: 30px; margin-bottom: 30px;">
                        <thead class="point-table-head">
                            <tr class="smaller-table">
                                <th class="text-left-head">Favorites</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                        {% for info in all_teams %}
                            <tr class="smaller-table">
                                <td class="custom-checkbox">
                                    <label >
                                        {% if info.team_id in current_teams %}
                                        <input type="checkbox" name="{{info.name}}" value="{{info.team_id}}" checked/>
                                        <i class="far fa-star" style="font-size: 30px; "></i>
                                        <i class="fas fa-star" style="font-size: 30px;"></i>
                                        {% else %}
                                        <input type="checkbox" name="{{info.name}}" value="{{info.team_id}}" />
                                        <i class="far fa-star" style="font-size: 30px; "></i>
                                        <i class="fas fa-star" style="font-size: 30px;"></i>
                                        {% endif %}
                                    </label>
                                </td><!--add team_id value to register when star is lit #{{info.team_id}}-->
                                <td class="text-left" style="width: 95%;"><img class="img-left" alt="Team logo" src="{{info.logo}}"><span>{{info.name}}</span></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div id="wrapper">
                    <button type="submit" class="button">Confirm</button></a>
                    </div>
                </form>
                </div>
            </div>

</div>


{% endblock content %}

users/templates/users/favorites.html
{% extends "users/base.html" %}
{%load static%}

{% block title %}
Favorites
{% endblock title %}

{% block content %} 
<section class="home" style="background-image: url(https://images.unsplash.com/photo-1585170236738-aadfce97f025?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxhbGx8fHx8fHx8fHwxNjIxNDA1MDU0&ixlib=rb-1.2.1&q=80&w=1080&utm_source=unsplash_source&utm_medium=referral&utm_campaign=api-credit);">
</section>

<div class="container paddings-mini" style="margin-right: 100px; margin-left: 100px; margin-bottom: 100px;">
    <h2 class="myH2">Favorites</h2>
    {% if search_result %}
        {% if search_result.success %}
            <div class="row">
                <div class="col-lg-12">
                {% regroup js_string_fav.response by date as result_list %}
                {% for res in result_list%}
                    <table class="table-striped table-responsive table-hover" style="width: 70%; margin-top: 30px; margin-bottom: 30px;">
                        <thead class="point-table-head">
                            <tr class="smaller-table">
                                <th class="text-left-head">{{res.grouper}}</th><!--{{result.fixture.date}}-->
                            </tr>
                        </thead>
                        <tbody class="text-center">
                        {% for result in res.list %}
                            <tr class="smaller-table">
                                <td class="text-right" style="padding: 10px 0px 10px 70px; width: 40%;"> <span>{{result.teams.home.name}}</span> <img class="img-right" alt="Team logo" src="{{result.teams.home.logo}}"> </td>
                              
                                {% if result.fixture.status.elapsed == NULL %}
                                    <td class="fill-container-time" style="width: 20%">{{result.time}}</td>
                                {% else %}
                                    <td class="fill-container" style="width: 20%">{{result.goals.home}} - {{result.goals.away}}</td>
                                {% endif %}
                          
                                <td class="text-left" style="padding: 10px 70px 10px 0px; width: 40%;"> <img class="img-left" alt="Team logo" src="{{result.teams.away.logo}}"> <span>{{result.teams.away.name}}</span> </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endfor %}
                    <div id="wrapper">
                        <a href="{% url 'users:editfavorites' %}" style="text-decoration: none; width:100%;"><button type="button" class="button button2">Edit Favorites</button></a>
                    </div>
                </div>
            </div>
            
        {% else %}
        <p><em>{{ search_result.message }}</em></p>
        {% endif %}
    {% endif %}
</div>

{% endblock content %}

users/templates/users/home.html
{% extends "users/base.html" %}
{%load static%}

{% block title %}
Home
{% endblock title %}

{% block content %}
<section class="home">
</section>

<div class="container paddings-mini" style="margin-right: 100px; margin-left: 100px; margin-bottom: 100px;">
    <h2 class="myH2">General Standings (2021/2022) </h2>
    {% if search_result %}
        {% if search_result.success %}
        <div class="row">
            <div class="col-lg-12">
                <table class="table-striped table-responsive table-hover" style="width: 75%">
                    <thead class="point-table-head">
                        <tr>
                            <th class="text-left-head">No</th>
                            <th class="text-left-head">TEAM</th>
                            <th class="text-left-head">MP</th>
                            <th class="text-left-head">W</th>
                            <th class="text-left-head">D</th>
                            <th class="text-left-head">L</th>
                            <th class="text-left-head">GF</th>
                            <th class="text-left-head">GA</th>
                            <th class="text-left-head">GD</th>
                            <th class="text-left-head">PTS</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for result in search_result.response %}
                        {% for teams in result.league.standings %}
                            {% for info in teams %}
                            <tr>
                                <td class="text-number">{{info.rank}}</td>
                                <td class="text-number"> <img class="img-left" alt="Team logo" src="{{info.team.logo}}"><span>{{info.team.name}}</span> </td>
                                <td class="text-number">{{info.all.played}}</td>
                                <td class="text-number">{{info.all.win}}</td>
                                <td class="text-number">{{info.all.draw}}</td>
                                <td class="text-number">{{info.all.lose}}</td>
                                <td class="text-number">{{info.all.goals.for}}</td>
                                <td class="text-number">{{info.all.goals.against}}</td>
                                <td class="text-number">{{info.goalsDiff}}</td>
                                <td class="text-number">{{info.points}}</td>
                            </tr>
                            {% endfor %}
                        {% endfor %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% else %}
        <p><em>{{ search_result.message }}</em></p>
        {% endif %}
    {% endif %}
</div>

{% endblock content %}

users/templates/users/login.html
<!DOCTYPE html>
{%load static%}
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'users/login.css' %}">
</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
                            <input type="password" name="password" placeholder="Password..." class="form-control">
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

                {% for message in messages %}
                <p id="messages">{{message}}</p>
                {% endfor%}            
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'users:signup' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

users/templates/users/matches.html
{% extends "users/base.html" %}
{%load static%}

{% block title %}
All Matches
{% endblock title %}

{% block content %}
<section class="home" style="background-image: url(https://images.unsplash.com/photo-1434648957308-5e6a859697e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTYyODM2NjA1MA&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=1080);">
</section>


<div class="container paddings-mini" style="margin-right: 100px; margin-left: 100px; margin-bottom: 100px;">
    <h2 class="myH2">Matches</h2>
    {% if search_result %}
        {% if search_result.success %}
            <div class="row">
                <div class="col-lg-12">
                {% regroup js_string.response by date as result_list %}
                {% for res in result_list%}
                    <table class="table-striped table-responsive table-hover" style="width: 70%; margin-top: 30px; margin-bottom: 30px;">
                        <thead class="point-table-head">
                            <tr class="smaller-table">
                                <th class="text-left-head">{{res.grouper}}</th><!--{{result.fixture.date}}-->
                            </tr>
                        </thead>
                        <tbody class="text-center">
                        {% for result in res.list %}
                            <tr class="smaller-table">
                                <td class="text-right" style="padding: 10px 0px 10px 70px; width: 40%;"> <span>{{result.teams.home.name}}</span> <img class="img-right" alt="Team logo" src="{{result.teams.home.logo}}"> </td>
                              
                                {% if result.fixture.status.elapsed == NULL %}
                                    <td class="fill-container-time" style="width: 20%">{{result.time}}</td>
                                {% else %}
                                    <td class="fill-container" style="width: 20%">{{result.goals.home}} - {{result.goals.away}}</td>
                                {% endif %}
                          
                                <td class="text-left" style="padding: 10px 70px 10px 0px; width: 40%;"> <img class="img-left" alt="Team logo" src="{{result.teams.away.logo}}"> <span>{{result.teams.away.name}}</span> </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endfor %}
                </div>
            </div>
            
        {% else %}
        <p><em>{{ search_result.message }}</em></p>
        {% endif %}
    {% endif %}
</div>

{% endblock content %}

users/templates/users/signup.html
<!DOCTYPE html>
{%load static%}
<html>
    
<head>
	<title>Sign Up</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'users/login.css' %}">
</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Sign Up</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Sign Up">
				   		</div>
					</form>
				</div>

                {{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'users:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Enter password...';
		form_fields[3].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>